# Generated by Django 5.0.4 on 2024-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releaseAt',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
    ]
