# Generated by Django 5.0.4 on 2024-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_releaseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releaseAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
